baseURL = 'https://ceazisgeorgescu.ro/'
languageCode = 'en-us'
title = 'Ce a zis Georgescu?'
theme = "papermod"
paginate = 1000



[params]
    mainSections = ["posts"]
    ShowReadingTime = false
    ShowPostNavLinks = true
    disableSpecial1stPost = true
    ogTitle = "Ce a zis Catalin Georgescu? | Principalele declaratii controversate"
    ogDescription = "O agregare a principalelor declaratii controversate ale candidatului la prezidentiale Calin Georgescu, impreuna cu sursa. Fiti informati!"
    ogImage = "../themes/papermod/images/geo.jpg" #(relative to the `static/` folder)

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Oare sunt manipulat?"
        url = "/manipulare/"
        weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
    home = ["HTML", "RSS", "JSON", "robotsTXT"]
