baseURL = 'https://ceazisgeorgescu.ro/'
languageCode = 'en-us'
title = 'Ce a zis Georgescu?'
theme = "papermod"
paginate = 1000


[params]
    mainSections = ["posts"]
    ShowReadingTime = false
    ShowPostNavLinks = true
    disableSpecial1stPost = true
    ogTitle = "Ce a zis Calin Georgescu? | Principalele declaratii controversate"
    ogDescription = "O agregare a principalelor declaratii controversate ale candidatului la prezidentiale Calin Georgescu, impreuna cu sursa. Fiti informati!"
    ogImage = "/images/geo2.jpeg" #(relative to the `static/` folder)
    privacy_policy_url = "/privacy-policy/"
    privacy_policy_text = "Privacy Policy"
    social = true

    [[params.socialIcons]]
      name = "Instagram"
      url = "https://www.instagram.com/ceazisgeorgescu"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Oare sunt manipulat?"
        url = "/manipulare/"
        weight = 2
    [[menu.main]]
        name = "Despre noi"
        url = "/despre/"
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
    home = ["HTML", "RSS", "JSON", "robotsTXT"]
